apiVersion: skaffold/v2beta5
kind: Config
metadata:
  name: mapviewer
build:
  artifacts:
    - image: nexus-docker-public-hosted.ossim.io/mapviewer
      # jib: {}
deploy:
  kubectl:
    manifests:
    - K8s/mapviewer-deployment.yaml
    - K8s/mapviewer-service.yaml
    - K8s/mapviewer-ingress.yaml
    #- k8s.yaml

   
